language: node_js
node_js: node
services: mongodb
env:
  matrix:
    - secure: EeR47pUVA91+S1jpBl6P3XvL71j3lSZN8F2BLZDTcPXjkMmWGwHFXS1DpvOjdgEvwjdNiVoVjPt9VwnP0cuThiqzpvXMJgrLYBVz5vjmqs9G3BnaPdwot4pwFBJMJTh4yLqiJJvaaRFbSYl3LMv+xv1yRAiKddtgPrOD1DRxrf0uQJa+lP+c8Wlo5MX2OTiOwYtqI/MYpPEaTV6IJsNcQOpWWwkGKzK/GJE/C7PdDKgydUT6z3cFF6MZMg0M+uGCJKDLqjAe7QZIRQu9zvAKmayGbdo2Fi43gYn1F1Jr6tEi0YBsYDKVm7v2DaJ2ibtzU370Jjr9N7SZg7GdUPZGk+EMibV0NSLU2qTcegAwtnApDqoRy++byA0WSLMT/zOPpF2//PicNVghPtvzuQq1+MTaWPQz7Qzxg9/ruBCg+9uEfi3r8dMWLbkAhAfmcwls3SDthe5qwil84bfM8yZEJddVbIdDPD2NNCmlbUaPBMgSh6MwqJhPeUN4RMkAQt/jDyVGxyoZ3bKX1KW0j12pPV8NNCxomMBEgKI6l96ziwPNWJfTRgtrgVD+smVeHho+fDI38Yj81bFK32k3c3nZ0Xlhh29tlvRpwUbV9EzBFC6HniAbaUq42w0wtkgvHsWNnLsigkrg0vrOieG5XIN8gRZ5dQnt3LMvG/UT0y5F+T0=
